export const extMap = {
  // Image files
  png: "png.png",
  jpg: "png.png",
  jpeg: "png.png",
  gif: "png.png",
  webp: "png.png",
  bmp: "png.png",
  svg: "png.png",
  ico: "png.png",
  tiff: "png.png",
  tif: "png.png",
  heic: "png.png",
  heif: "png.png",
  raw: "png.png",
  cr2: "png.png",
  nef: "png.png",
  orf: "png.png",
  sr2: "png.png",
  arw: "png.png",
  dng: "png.png",

  // Video files
  mp4: "mp4.png",
  avi: "mp4.png",
  mov: "mp4.png",
  mkv: "mp4.png",
  webm: "mp4.png",
  flv: "mp4.png",
  wmv: "mp4.png",
  m4v: "mp4.png",
  mpg: "mp4.png",
  mpeg: "mp4.png",
  "3gp": "mp4.png",
  ogv: "mp4.png",
  vob: "mp4.png",
  ts: "mp4.png",
  mts: "mp4.png",
  m2ts: "mp4.png",

  // Audio files
  mp3: "mp3.png",
  wav: "mp3.png",
  ogg: "mp3.png",
  flac: "mp3.png",
  aac: "mp3.png",
  wma: "mp3.png",
  m4a: "mp3.png",
  opus: "mp3.png",
  aiff: "mp3.png",
  au: "mp3.png",

  // PDF
  pdf: "pdf.png",

  // Microsoft Word
  doc: "word.png",
  docx: "word.png",
  docm: "word.png",
  dot: "word.png",
  dotx: "word.png",
  rtf: "word.png",
  odt: "word.png",

  // Microsoft Excel
  xls: "xls.png",
  xlsx: "xls.png",
  xlsm: "xls.png",
  xlsb: "xls.png",
  xlt: "xls.png",
  xltx: "xls.png",
  csv: "xls.png",
  ods: "xls.png",

  // Microsoft PowerPoint
  ppt: "ppt.png",
  pptx: "ppt.png",
  pptm: "ppt.png",
  pot: "ppt.png",
  potx: "ppt.png",
  odp: "ppt.png",

  // Archive files
  zip: "zip.png",
  rar: "zip.png",
  "7z": "zip.png", // 7z file extension
  tar: "zip.png",
  gz: "zip.png",
  bz2: "zip.png",
  xz: "zip.png",
  z: "zip.png",
  ace: "zip.png",
  arj: "zip.png",
  cab: "zip.png",
  dmg: "zip.png",
  iso: "zip.png",
  jar: "zip.png",
  war: "zip.png",
  ear: "zip.png",

  // Text files
  txt: "txt.png",
  md: "txt.png",
  markdown: "txt.png",
  log: "txt.png",
  ini: "txt.png",
  cfg: "txt.png",
  conf: "txt.png",
  properties: "txt.png",
  readme: "txt.png",

  // Code files
  html: "html.png",
  htm: "html.png",
  css: "html.png",
  js: "html.png",
  jsx: "html.png",
  ts: "html.png",
  tsx: "html.png",
  vue: "html.png",
  svelte: "html.png",
  php: "html.png",
  py: "html.png",
  java: "html.png",
  c: "html.png",
  cpp: "html.png",
  cc: "html.png",
  cxx: "html.png",
  h: "html.png",
  hpp: "html.png",
  cs: "html.png",
  go: "html.png",
  rs: "html.png",
  rb: "html.png",
  swift: "html.png",
  kt: "html.png",
  scala: "html.png",
  clj: "html.png",
  sh: "html.png",
  bash: "html.png",
  zsh: "html.png",
  fish: "html.png",
  ps1: "html.png",
  bat: "html.png",
  cmd: "html.png",
  xml: "html.png",
  json: "html.png",
  yaml: "html.png",
  yml: "html.png",
  toml: "html.png",

  // Database
  sql: "sql.png",
  db: "sql.png",
  sqlite: "sql.png",
  sqlite3: "sql.png",
  mdb: "sql.png",
  accdb: "sql.png",
  dbf: "sql.png",

  // Design files
  psd: "psd.png",
  ai: "Ai.png",
  sketch: "sketch.png",
  fig: "fig.png",
  xd: "fig.png",
  indd: "inndd.png",
  ae: "ae.png",
  aep: "ae.png",
  aet: "ae.png",
  prproj: "ae.png",
  premiere: "ae.png",

  // 3D files
  "3d": "3d.png",
  obj: "3d.png",
  fbx: "3d.png",
  dae: "3d.png",
  blend: "3d.png",
  max: "3d.png",
  ma: "3d.png",
  mb: "3d.png",
  c4d: "3d.png",
  stl: "3d.png",
  ply: "3d.png",
  x3d: "3d.png",
  gltf: "3d.png",
  glb: "3d.png",

  // Calendar
  cal: "cal.png",
  ics: "cal.png",

  // Email
  eml: "eml.png",
  msg: "eml.png",

  // Other
  locked: "locked.png",
  folder: "folder.png",
};
